# Generated by Django 6.0.6 on 2026-06-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('north goa', 'North Goa'), ('south goa', 'South Goa'), ('kushavati', 'Kushavati')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
