# Generated by Django 6.0.6 on 2026-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='badge',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
