# Generated by Django 6.0.6 on 2026-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price_label',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
