# Generated by Django 6.0.6 on 2026-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_pincode_property_price_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='builtup_area',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='full_address',
            field=models.TextField(default=1, help_text='Enter your complete address', verbose_name='Full Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertynearby',
            name='icon',
            field=models.CharField(choices=[('🏖️', 'Beach'), ('🌊', 'Waterfront'), ('✈️', 'Airport'), ('🏥', 'Hospital'), ('🛒', 'Shopping'), ('🌧️', 'Waterfall')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
