# Generated by Django 6.0.6 on 2026-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_builtup_area_property_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertynearby',
            name='short_description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertynearby',
            name='distance',
            field=models.CharField(max_length=20),
        ),
    ]
