# Generated by Django 6.0.6 on 2026-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertynearby_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyamenity',
            name='icon',
            field=models.CharField(choices=[('♾️', 'Swimming Pool'), ('🌬️', 'Central AC'), ('📶', 'Wifi'), ('🏥', 'Hospital'), ('🛒', 'Shopping'), ('🌧️', 'Waterfall'), ('🚗', 'Parking'), ('🌿', 'Garden'), ('🚿', 'Shower'), ('🛁', 'Jacuzzi '), ('🌅', 'Sea-View '), ('🚿', 'TV'), ('💧', 'Water'), ('⚡', 'Backup')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
