# Generated by Django 6.0.6 on 2026-06-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertyamenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyhighlight',
            name='icon',
            field=models.CharField(choices=[('♾️', 'Swimming Pool'), ('🌬️', 'Central AC'), ('📶', 'Wifi'), ('🏥', 'Hospital'), ('🛒', 'Shopping'), ('🌧️', 'Waterfall'), ('🚗', 'Parking'), ('🌿', 'Garden'), ('🚿', 'Shower'), ('🛁', 'Jacuzzi '), ('🌅', 'Sea-View '), ('🚿', 'TV'), ('💧', 'Water'), ('⚡', 'Backup'), ('🏠', 'Home'), ('🔒', 'Secure'), ('☀️', 'Sun'), ('🏖️', 'Beach')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
