# Generated by Django 6.0.6 on 2026-06-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertyhighlight_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylegalinfo',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylegalinfo',
            name='icon',
            field=models.CharField(choices=[('📄', 'Document'), ('🌊', 'Sea'), ('🔍', 'Glass'), ('🏛️', 'Building'), ('🏗️', 'Construction'), ('🌍', 'Earth'), ('🚗', 'Parking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertylegalinfo',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
