# Generated by Django 6.0.6 on 2026-06-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertylegalinfo_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='image',
            new_name='gallery_images',
        ),
    ]
