# Generated by Django 6.0.6 on 2026-06-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_rename_image_propertyimage_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='view_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
