# Generated by Django 6.0.6 on 2026-06-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_inquiry_is_contacted_inquiry_view_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoViewingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('WhatsApp Video', 'WhatsApp Video'), ('Google Meet', 'Google Meet'), ('Zoom', 'Zoom'), ('FaceTime', 'FaceTime')], max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_requests', to='properties.property')),
            ],
        ),
    ]
