# Generated by Django 6.0.6 on 2026-06-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_videoviewingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rera_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
